data:
  name: "cifar100"
  batch_size: 2048
  num_workers: 4
  split: [0.9, 0.1]

trainer:
  seed: 42
  sch: "cosine_annealing_lr"
  epochs: 200

model:
  architecture: "resnet18"
  name: "hsam"
  lr: 0.1
  momentum: 0.9
  weight_decay: 0.001
  rho: 2
  hsam_beta: 0.99
  adaptive: False
  nesterov: False

wandb:
  name: "resnet18_hsam_hrho1_beta2_099_rho2_bs2048_seed42"
  project: SAM-Adaptive-Rho-CIFAR100
