data:
  name: "fashion_mnist"
  batch_size: 128
  num_workers: 4
  split: [0.9, 0.1]

trainer:
  seed: 42
  sch: "cosine_annealing_lr"
  epochs: 200

model:
  architecture: "resnet18_mnist"
  name: "sam"
  lr: 0.1
  momentum: 0.9
  weight_decay: 0.001
  rho: 0.05
  adaptive: False
  nesterov: False

wandb:
  name: "resnet18_rho005_momentum09_bs128_seed42"
  project: "SAM-Momentum-Fashion-MNIST"

