data:
  batch_size: 128
  name: fashion_mnist
  num_workers: 4
  split:
  - 0.9
  - 0.1
model:
  adaptive: false
  architecture: "resnet34_mnist"
  lr: 0.1
  momentum: 0.9
  name: sam
  nesterov: false
  rho: 0.05
  weight_decay: 0.001
trainer:
  epochs: 200
  sch: cosine_annealing_lr
  seed: 42
wandb:
  name: resnet34_rho005_momentum09_bs128_seed42
  project: SAM-Momentum-Fashion-MNIST
