data:
  name: "cifar100"
  batch_size: 128
  num_workers: 4
  split: [0.9, 0.1]

trainer:
  seed: 42
  sch: "cosine_annealing_lr"
  epochs: 200

model:
  architecture: "resnet18"
  name: "msam"
  lr: 0.1
  momentum: 0.1
  weight_decay: 0.001
  rho: 0.05
  nesterov: False

wandb:
  name: "resnet18_msam_rho005_momen01_bs128_seed42"
  project: SAM-Adaptive-Rho-CIFAR100
