data:
  batch_size: 128
  name: cifar100
  num_workers: 4
  split:
  - 0.9
  - 0.1
model:
  adaptive: false
  architecture: resnet18
  lr: 0.1
  momentum: 0.0
  name: sama
  nesterov: false
  rho: 0.05
  weight_decay: 0.001
  betas: [0.9, 0.9]
trainer:
  epochs: 200
  sch: constant_lr
  factor: 1
  total_iters: 200
  seed: 42
wandb:
  name: "{model.architecture}_{model.name}_rho{model.rho}_constlr_momen{model.momentum}_betas{model.betas[0]}_{model.betas[1]}_{data.batch_size}_seed{trainer.seed}"
  project: SAM-Adaptive-Rho-CIFAR100
