data:
  name: "cifar10"
  batch_size: 16
  num_workers: 4
  split: [0.9, 0.1]

trainer:
  seed: 42
  sch: "cosine_annealing_lr"
  epochs: 400

model:
  architecture: "resnet18"
  name: "sam"
  lr: 0.1
  momentum: 0.9
  weight_decay: 0.001
  rho: 0.05
  adaptive: False
  nesterov: False

wandb:
  name: "resnet18_bs16_seed42"
  project: "SAM-Saddle-Point-CIFAR10"

