data:
  batch_size: 128
  name: cifar100
  num_workers: 4
  split:
  - 0.9
  - 0.1
model:
  adaptive: false
  architecture: wrn28_10
  lr: 0.1
  momentum: 0.9
  name: sam
  nesterov: false
  rho: 0.8
  weight_decay: 0.001
trainer:
  epochs: 200
  sch: cosine_annealing_lr
  seed: 42
  warmup: 200
wandb:
  name: wrn28_10_rho08_warmup200_bs128_seed42
  project: SAM-ECCV-CIFAR100
