data:
  name: "cifar10"
  batch_size: 1024
  num_workers: 4
  split: [0.9, 0.1]

trainer:
  seed: 42
  sch: "cosine_annealing_lr"
  epochs: 200

model:
  architecture: "resnet18"
  name: "hsam"
  lr: 0.1
  momentum: 0.9
  weight_decay: 0.001
  rho: 0.05
  hsam_beta: 0.95
  adaptive: False
  nesterov: False

wandb:
  name: "resnet18_hsam_bs1024_seed42"
  project: "SAM-Saddle-Point-CIFAR10"

