data:
  name: "cifar10"
  batch_size: 32
  num_workers: 4
  split: [0.9, 0.1]

trainer:
  seed: 42
  sch: "cosine_annealing_lr"
  epochs: 200

model:
  architecture: "resnet18"
  name: "sgd"
  lr: 0.1
  momentum: 0.9
  weight_decay: 0.0005

wandb:
  name: "sgd_resnet18_bs32_seed42"
  project: "SAM-Saddle-Point-CIFAR10"

