data:
  name: "cifar10"
  batch_size: 128
  num_workers: 4
  split: [0.9, 0.1]

trainer:
  seed: 42
  sch: "cosine_annealing_lr"
  epochs: 200

model:
  architecture: "resnet34"
  name: "dnsam"
  lr: 0.1
  momentum: 0.9
  weight_decay: 0.001
  rho: 0.05
  adaptive: False
  nesterov: False
  dnsam_theta: 0.1

wandb:
  name: "resnet34_dnsam01_bs128_seed42"
  project: "SAM-Saddle-Point-CIFAR10"

