data:
  name: "cifar100"
  batch_size: 128
  num_workers: 4
  split: [0.9, 0.1]

trainer:
  seed: 42
  sch: "cosine_annealing_lr"
  epochs: 200
  warmup: 20

model:
  architecture: "resnet18"
  name: "sam"
  lr: 0.1
  momentum: 0.9
  weight_decay: 0.001
  rho: 1
  adaptive: False
  nesterov: False

wandb:
  name: "resnet18_rho1_warmup20_bs128_seed42"
  project: "SAM-Saddle-Point-CIFAR100"

